GET http://localhost:8080/products

###
DELETE http://localhost:8080/products/6183131b2ff5fda3fb58d838


###
PATCH http://localhost:8080/products/
Content-Type: application/json

{
"name":"Rug",
"price":"999",
"description":"lorem ipsum",
"category":"livingRoom",
"images":["https://cdn.pixabay.com/photo/2018/05/02/09/02/baby-boy-3368017__340.jpg","https://cdn.pixabay.com/photo/2018/05/02/09/02/baby-boy-3368017__340.jpg"]

}

###
POST  http://localhost:8080/products
Content-Type: application/json

{


}

###
GET http://localhost:8080/carts/6183162cd7907e590851e05a

###

POST http://localhost:8080/carts
Content-Type: application/json

{
"name":"third cart"

}

###

PATCH  http://localhost:8080/carts/add/6183162cd7907e590851e05a
Content-Type: application/json

{
"name":"somethinggg",
"products":"lklkl"
}

###
GET http://localhost:8080/contacts

###
POST http://localhost:8080/contacts
Content-Type: application/json

{
"name": "new contact"

}
